import { Product, StoreSettings, PaymentConfig, DeliveryAgent } from './types';

export const SUPABASE_URL = "https://aqihwumjlzpzyazxvazw.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_pND8EMf5EOGIJGFjYKyufw_qaHv4Os-";
export const SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY;

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: "DealKart",
  tagline: "Deals Beyond Ordinary",
  announcementText: "⚡ FLASH SALE: Extra 20% OFF with code MEGA20 at Checkout · Free Express Cash on Delivery",
  showAnnouncement: true,
  heroTitle: "Great Finds. Better Prices.",
  heroSubtitle: "Shop Smarter. Save More.",
  heroBadgeText: "Up To 80% Off · Limited Time · Top Brands",
  heroImageUrl: "/src/assets/images/dealkart_hero_banner_1791110791232.jpg",
  currencySymbol: "$",
  currencyCode: "USD",
  supportEmail: "support@dealkart.store",
  supportPhone: "+1 (800) 555-DEAL",
};

export const INITIAL_PAYMENT_CONFIG: PaymentConfig = {
  enableCod: true,
  codExtraFee: 0,
  enableUpiQr: true,
  upiId: "dealkart@upi",
  upiMerchantName: "DealKart Verified Merchant",
  upiQrImageUrl: "/src/assets/images/payment_upi_qr_1791110801850.jpg",
  enableBankTransfer: true,
  bankDetails: "DealKart Inc. - Silicon Bank, Account: 9876543210, Routing/IFSC: SBIN000492",
  enableCard: true,
};

export const INITIAL_DELIVERY_AGENTS: DeliveryAgent[] = [
  {
    id: "da-1",
    name: "Alex Martinez",
    phone: "+1 (555) 234-8901",
    zone: "Metro Downtown & Financial",
    vehicle: "Express Van #04",
    status: "active",
    totalCashCollected: 459.80,
  },
  {
    id: "da-2",
    name: "Marcus Vance",
    phone: "+1 (555) 871-3329",
    zone: "North Hills & Suburbs",
    vehicle: "Electric Cargo Bike #12",
    status: "on_delivery",
    totalCashCollected: 319.50,
  },
  {
    id: "da-3",
    name: "Samira Patel",
    phone: "+1 (555) 612-4498",
    zone: "East Riverside & Harbor",
    vehicle: "Transit Courier #09",
    status: "active",
    totalCashCollected: 680.00,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Daily Deals
  {
    id: "dd-1",
    name: "True Wireless Earbuds",
    category: "Electronics",
    price: 29.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviewCount: 342,
    discountBadge: "-62%",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=60",
    description: "Active noise cancellation, 32-hour battery life with charging case, water-resistant IPX5.",
    isDailyDeal: true,
    variants: ["Midnight Black", "Pearl White", "Navy Blue"],
  },
  {
    id: "dd-2",
    name: "Smart Coffee Maker",
    category: "Home & Living",
    price: 49.99,
    originalPrice: 96.99,
    rating: 4.9,
    reviewCount: 289,
    discountBadge: "-48%",
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500&auto=format&fit=crop&q=60",
    description: "Programmable digital brewer with insulated thermal carafe and auto-keep-warm.",
    isDailyDeal: true,
    variants: ["Brushed Steel", "Matte Obsidian"],
  },
  {
    id: "dd-3",
    name: "Smart Watch Pro",
    category: "Accessories",
    price: 79.99,
    originalPrice: 179.99,
    rating: 4.8,
    reviewCount: 512,
    discountBadge: "-55%",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60",
    description: "AMOLED curved display, heart rate & SpO2 tracking, sleep monitor, 7-day battery.",
    isDailyDeal: true,
    variants: ["Rose Gold", "Space Black", "Titanium Silver"],
  },
  {
    id: "dd-4",
    name: "LED Mood Lamp",
    category: "Home & Living",
    price: 23.99,
    originalPrice: 39.99,
    rating: 4.9,
    reviewCount: 198,
    discountBadge: "-40%",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&auto=format&fit=crop&q=60",
    description: "Touch dimmable ambient bedside lighting with warm 2700K soothing glow.",
    isDailyDeal: true,
    variants: ["Warm Amber", "Soft White"],
  },

  // Popular Products
  {
    id: "pop-1",
    name: "Premium Casual Shirt",
    category: "Fashion",
    price: 34.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviewCount: 180,
    discountBadge: "-42%",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop&q=60",
    description: "100% breathable organic linen-cotton blend. Tailored modern relaxed fit.",
    isPopular: true,
    variants: ["Sky Blue (M)", "Sky Blue (L)", "Classic White (L)", "Navy (XL)"],
  },
  {
    id: "pop-2",
    name: "Digital Air Fryer 5.5L",
    category: "Home & Living",
    price: 89.99,
    originalPrice: 139.99,
    rating: 4.9,
    reviewCount: 420,
    discountBadge: "-35%",
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500&auto=format&fit=crop&q=60",
    description: "360-degree rapid heat air circulation, 8 preset cooking modes, dishwasher-safe basket.",
    isPopular: true,
    variants: ["Matte Black", "Stainless Silver"],
  },
  {
    id: "pop-3",
    name: "Hydrating Skincare Set",
    category: "Beauty",
    price: 39.99,
    originalPrice: 65.00,
    rating: 4.9,
    reviewCount: 310,
    discountBadge: "-38%",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=60",
    description: "Rosewater toner, hyaluronic acid essence, and peptide moisture barrier repair cream.",
    isPopular: true,
    variants: ["3-Piece Essential Kit", "5-Piece Luxury Deluxe"],
  },
  {
    id: "pop-4",
    name: "Bluetooth Rugged Speaker",
    category: "Electronics",
    price: 59.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviewCount: 220,
    discountBadge: "-40%",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format&fit=crop&q=60",
    description: "30W deep bass dual passive radiators, 24h battery life, IP67 waterproof & dustproof.",
    isPopular: true,
    variants: ["Stealth Black", "Army Green", "Electric Red"],
  },
  {
    id: "pop-5",
    name: "Ergonomic Office Chair",
    category: "Home & Living",
    price: 149.99,
    originalPrice: 249.99,
    rating: 4.9,
    reviewCount: 165,
    discountBadge: "-40%",
    image: "https://images.unsplash.com/photo-1580481077195-c322b77a16f0?w=500&auto=format&fit=crop&q=60",
    description: "Adjustable 3D lumbar support, breathable Korean mesh, 135-degree recline mechanism.",
    isPopular: true,
    variants: ["Charcoal Grey", "Pure Black"],
  },
  {
    id: "pop-6",
    name: "Noise-Cancel Headphones",
    category: "Electronics",
    price: 99.99,
    originalPrice: 199.99,
    rating: 4.8,
    reviewCount: 388,
    discountBadge: "-50%",
    image: "/src/assets/images/cod_product_headphones_1791110099717.jpg",
    description: "Custom 40mm beryllium acoustic drivers, 50-hour battery, memory foam earcups.",
    isPopular: true,
    variants: ["Matte Graphite", "Champagne Gold", "Arctic Silver"],
  },

  // Limited Drops
  {
    id: "drop-1",
    name: "Retro Sneaker Drop",
    category: "Fashion",
    price: 119.99,
    originalPrice: 180.00,
    rating: 4.9,
    reviewCount: 94,
    discountBadge: "Rare",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500&auto=format&fit=crop&q=60",
    description: "Limited collector run. Vintage aged leather upper with gum rubber outsole.",
    isLimitedDrop: true,
    stockLeft: 500,
    variants: ["US 9", "US 10", "US 11", "US 12"],
  },
  {
    id: "drop-2",
    name: "Anime Collectible Figurine",
    category: "Toys & Hobbies",
    price: 49.99,
    originalPrice: 75.00,
    rating: 4.9,
    reviewCount: 140,
    discountBadge: "Exclusive",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=60",
    description: "Hand-painted PVC collector piece with magnetic display base and serial certificate.",
    isLimitedDrop: true,
    stockLeft: 300,
    variants: ["Standard Edition", "Metallic Finish"],
  },
  {
    id: "drop-3",
    name: "Heritage Automatic Watch",
    category: "Accessories",
    price: 189.99,
    originalPrice: 320.00,
    rating: 4.9,
    reviewCount: 88,
    discountBadge: "Limited",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&auto=format&fit=crop&q=60",
    description: "Japanese 24-jewel automatic movement, sapphire crystal glass, genuine calfskin band.",
    isLimitedDrop: true,
    stockLeft: 200,
    variants: ["Gold / Brown Leather", "Silver / Black Leather"],
  },
  {
    id: "drop-4",
    name: "Designer Handbag",
    category: "Fashion",
    price: 139.99,
    originalPrice: 220.00,
    rating: 4.8,
    reviewCount: 110,
    discountBadge: "Designer",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&auto=format&fit=crop&q=60",
    description: "Saffiano full-grain Italian leather, gold-tone hardware, detachable shoulder strap.",
    isLimitedDrop: true,
    stockLeft: 150,
    variants: ["Burgundy Crimson", "Classic Cognac", "Midnight Noir"],
  },
];
